### ISSUE TITLE
enable new cops by default

### ISSUE THREAD

**Issue by swiknaba** [dbl-works/rubocop-dbl#18]
```
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file.

Please also note that can also opt-in to new cops by default by adding this to your config:
  AllCops:
    NewCops: enable

Layout/SpaceBeforeBrackets: # (new in 1.7)
  Enabled: true
Lint/AmbiguousAssignment: # (new in 1.7)
  Enabled: true
Style/HashExcept: # (new in 1.7)
  Enabled: true
For more information: https://docs.rubocop.org/rubocop/versioning.html
```
